[package]
name = "skeleton_example_bindings"
version = "0.0.0"
edition = "2018"

[dependencies]
windows = "0.11.0"
project_reunion = { path = "../../../" }

[build-dependencies]
windows = "0.11.0"
project_reunion = { path = "../../../" }